---
title: "NMF_simulations"
author: "Jared Slosberg"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load, message = F}

require(scater)
require(NNLM)
require(ComplexHeatmap)
require(circlize)
require(assertthat)
library(dplyr)
library(purrr)
library(stringr)
library(monocle3)
library(glmpd)


```

```{r, echo = F}
#define modulo for 1 indexed vectors
pred <- function(n) n - 1L
succ <- function(n) n + 1L
`%mod1%` <- function(m, n) succ(pred(m) %% n) # modulo from 1

movingAverage <- function(x, n){stats::filter(x, rep(1 / n, n), sides = 2, circular = T)}

#TODO: rewrite as cell weights so that genes can be reused?
createGeneWeights <- function(num_patterns, num_genes_per_pattern, value = c(0,1), circ_smooth_n = NULL){
  gene_weights__list <- purrr::map(1:num_patterns, function(pattern_no){
  
    num_genes <- num_patterns * num_genes_per_pattern
    
    #number of genes 
    spacer <- num_genes_per_pattern
    
    #initialize zeros of proper length
    vec <- rep(value[1], num_genes)
    
    vec[((pattern_no-1)*spacer+1):(pattern_no*spacer)] <- value[2]
  return(vec)
  })
  
  gene_weights<- gene_weights__list %>% dplyr::bind_cols() %>% as.matrix()
  colnames(gene_weights) <- paste0("fake_pattern",1:num_patterns)
  
  if(!is.null(circ_smooth_n)){
    gene_weights <- apply(gene_weights, MARGIN = 2,  function(x){movingAverage(x, circ_smooth_n)})

  }
  return(gene_weights)
  
}

createCellWeights <- function(num_patterns, num_patterns_used, num_cells_per_pattern, value = c(0,1), circ_smooth_n = NULL){
  cell_weights_list <- purrr::map(1:num_patterns, function(pattern_no){
  
    #define indices for columns to be non-zero
    pattern_ind_vec <- pattern_no:(pattern_no + num_patterns_used - 1) %mod1% num_patterns
    
    mat <- matrix(data = value[1], num_cells_per_pattern,num_patterns)
    mat[,pattern_ind_vec] <- value[2]
  
  return(mat)
  })
  
  cell_weights <- cell_weights_list %>% do.call(rbind, . )
  colnames(cell_weights) <- paste0("fake_pattern",1:num_patterns)
  
  if(!is.null(circ_smooth_n)){
    cell_weights <- apply(cell_weights, MARGIN = 2,  function(x){movingAverage(x, circ_smooth_n)})
   
  }
  return(cell_weights)
}

```
#Can I construct the patterns in the latent space and use matrix multiplication to reconstruct the corresponding genes expression matrices?
```{r from_NMF_to_expression}
no_patterns <- 4
no_patterns_used <- 2

no_cells_per_pattern <- 20
total_cells <- no_patterns * no_cells_per_pattern
no_genes_per_pattern <- 100
total_genes <- no_patterns * no_genes_per_pattern

cell_weights_fake <- createCellWeights(num_patterns = no_patterns,
                                       num_patterns_used = no_patterns_used,
                                       num_cells_per_pattern = no_cells_per_pattern,
                                       value = c(0,10),
                                       circ_smooth_n = 50)

gene_weights_fake <- createGeneWeights(num_patterns = no_patterns,
                                       num_genes_per_pattern = no_genes_per_pattern,
                                       value = c(0,10),
                                       circ_smooth_n = NULL)


gene_color_scale <- circlize::colorRamp2(quantile(gene_weights_fake, c(0,.5,0.99)), c("grey","orange","red"))
cell_color_scale <- circlize::colorRamp2(quantile(cell_weights_fake, c(0,.5,0.99)), c("grey","orange","red"))


ComplexHeatmap::Heatmap(gene_weights_fake,
                        name = "gene_weights",
                        col = gene_color_scale,
                        row_names_gp = gpar(fontsize = 4), 
                        cluster_columns = F,
                        cluster_rows =F)
ComplexHeatmap::Heatmap(cell_weights_fake,
                        name = "cell_weights",
                        col = cell_color_scale,
                        row_names_gp = gpar(fontsize = 4),
                        cluster_columns = F,
                        cluster_rows= F)

exprs <- gene_weights_fake %*% t(cell_weights_fake)
#same cells and genes as in matrix?
colnames(exprs) <- paste0("cell",1:total_cells)
rownames(exprs) <- paste0("gene", 1:total_genes)
# smooth_exprs<- gene_weights_smooth %*% t(cell_weights_smooth)

```

```{r dimRed}
fake_sce <- SingleCellExperiment(assays = list(counts = exprs))


# colnames(gene_weights_fake) <- paste0("NMF_pattern",1:num_patterns)
# assert_that(rownames(gene_weights_fake) == rownames(rowData(fake_sce)) && T)
rowData(fake_sce) <- cbind(rowData(fake_sce), gene_weights_fake)
rowData(fake_sce)$gene_id <- rownames(fake_sce)

# colnames(cell_weights_fake) <- paste0("NMF_pattern",1:num_patterns)
# assert_that(rownames(cell_weights) == rownames(colData(fake_sce)) && T)
colData(fake_sce) <- cbind(colData(fake_sce), cell_weights_fake)
colData(fake_sce)[,"cell_number"] <- as.integer(str_split_fixed(colnames(fake_sce), "cell",2)[,2]) #integer cell number


p1a <- ComplexHeatmap::Heatmap(exprs, cluster_rows = F, cluster_columns = F, column_title = "expression without noise")


fake_sce <- scater::logNormCounts(fake_sce)
fake_sce <- runPCA(fake_sce)
p2a <- plotReducedDim(fake_sce, dimred = "PCA", colour_by = "cell_number") + ggtitle("PCA embedding without noise")

fake_sce <- runUMAP(fake_sce, ncomponents = 50)
p3a <- plotReducedDim(fake_sce, dimred = "UMAP") + ggtitle("UMAP embedding without noise")


##This time with noise
noise_mean <- 50
noise_sd <- 10
noise <- rnorm(total_cells*total_genes, mean = noise_mean, sd = noise_sd) %>%
  abs() %>%
  matrix(., nrow = total_genes, ncol= total_cells)

noisy_exprs <- exprs + noise

noisy_sce <- SingleCellExperiment(assays = list(counts = noisy_exprs))

rowData(noisy_sce) <- cbind(rowData(fake_sce), gene_weights_fake)
rowData(noisy_sce)$gene_id <- rownames(noisy_sce)

# colnames(cell_weights_fake) <- paste0("NMF_pattern",1:num_patterns)
# assert_that(rownames(cell_weights) == rownames(colData(fake_sce)) && T)
colData(noisy_sce) <- cbind(colData(noisy_sce), cell_weights_fake)
colData(noisy_sce)[,"cell_number"] <- as.integer(str_split_fixed(colnames(noisy_sce), "cell",2)[,2]) #integer cell number

noise_term <- paste0("~ norm(mean = ",noise_mean,", sd = ",noise_sd,")")
p1b <- ComplexHeatmap::Heatmap(noisy_exprs,
                               cluster_rows = F,
                               cluster_columns = F,
                               column_title = paste0("expression with noise ", noise_term))


noisy_sce <- scater::logNormCounts(noisy_sce)
noisy_sce <- runPCA(noisy_sce)
p2b <- plotReducedDim(noisy_sce, dimred = "PCA", colour_by = "cell_number") +
  ggtitle(paste0("PCA embedding with noise ", noise_term))

noisy_sce <- runUMAP(noisy_sce, ncomponents = 50)
p3b <- plotReducedDim(noisy_sce, dimred = "UMAP") +
  ggtitle(paste0("UMAP embedding with noise ", noise_term))

p1a
p2a
p3a
p1b
p2b
p3b


```

```{r plot_NMF_usage_fake}
pattern_usage_plots <-lapply(1:no_patterns, function(pattern_no){
  plotReducedDim(fake_sce, dimred = "UMAP", colour_by = paste0("fake_pattern",pattern_no))
})

print(pattern_usage_plots)

pattern_usage_plots <-lapply(1:no_patterns, function(pattern_no){
  plotReducedDim(noisy_sce, dimred = "UMAP", colour_by = paste0("fake_pattern",pattern_no)) + 
    ggtitle(paste0("UMAP embedding with noise ", noise_term))
})

print(pattern_usage_plots)

```

```{r glmpd, eval = T}


model_str <- paste0("~0 + patternWeights + sizeFactor")

#specify parameters for fittings
exp_family <- "negbinomial"

pattern_wts <- colData(fake_sce) %>% as.data.frame %>% dplyr::select(starts_with("fake_pattern"))

system.time(glm_models_list <- glmpd::fitGLMpd(object = fake_sce,
                                             model_formula_str = model_str,
                                             projected_patterns = pattern_wts,
                                             cores = 1, 
                                             count_assay = "counts"))

extracted_coefficients_list <- extractCoefficients(glm_models = glm_models_list, genes = rownames(fake_sce))

gene_coefficients_list <- orderCoefficientsByGene(extracted_coefficients_list, filter_significance = NULL, string = NULL)

coefficient_matrix_list <- organizeEstimates(gene_coefficients_list, 
                                             terms_exact = NULL,  
                                             terms_match = c("patternWeights", "log10UMI"),
                                             feature = "estimate",
                                             transpose = T,
                                             gene_name = "gene_id")
```

